#ifndef PAGE_NAVIGATION_DEFINS_H
#define PAGE_NAVIGATION_DEFINS_H
#pragma once

#include <QFlag>

namespace PageNavigation
{
	const int CURRENT_PAGE_NUMBER = 20;
	const int BUTTON_NUMBER = 9;

	enum DISPLAY_STATUS
	{
		INVAILD = 0,
		PAGE_NORMAL,
		PAGE_GUIDE_LEFT,
		PAGE_GUIDE_RIGHT,
		SELECT_NUMBER
	};

	enum NUMBER_TYPE
	{
		NORMAL_NUMBER = 1,
		GUIDE_LEFT_NUMBER,
		GUIDE_RIGHT_NUMBER
	};

	Q_DECLARE_FLAGS(Display, DISPLAY_STATUS)
	Q_DECLARE_OPERATORS_FOR_FLAGS(Display)
	Q_DECLARE_FLAGS(NumberType, NUMBER_TYPE)
	Q_DECLARE_OPERATORS_FOR_FLAGS(NumberType)
}

#endif // PAGE_NAVIGATION_DEFINS_H